// 떡 상품 데이터 — 떡담 플랫폼 전체에서 사용
// 각 상품은 id, name, nameEn, description, price, originalPrice, category, vendorId, image, tags, weight, rating, reviewCount, isNew, isBest 필드를 포함

export const products = [
  {
    id: 1,
    name: '송편',
    nameEn: 'Songpyeon',
    description: '한가위 대표 떡. 솔잎 향이 은은하게 배어든 송편입니다. 깨, 콩, 밤 등 다양한 소로 정성껏 빚었습니다.',
    price: 15000,
    originalPrice: 18000,
    category: 'seasonal',
    vendorId: 1,
    image: 'https://images.unsplash.com/photo-1573470571028-a0ca7a723959?w=600&h=450&fit=crop',
    tags: ['추석', '전통', '인기'],
    weight: '500g',
    rating: 4.8,
    reviewCount: 124,
    isNew: false,
    isBest: true,
  },
  {
    id: 2,
    name: '인절미',
    nameEn: 'Injeolmi',
    description: '고소한 콩가루를 듬뿍 묻힌 쫄깃한 인절미. 찹쌀의 진한 맛과 고소함이 일품입니다.',
    price: 12000,
    originalPrice: null,
    category: 'traditional',
    vendorId: 1,
    image: 'https://images.unsplash.com/photo-1628441309764-794e7362f6e6?w=600&h=450&fit=crop',
    tags: ['전통', '베스트', '고소함'],
    weight: '600g',
    rating: 4.9,
    reviewCount: 256,
    isNew: false,
    isBest: true,
  },
  {
    id: 3,
    name: '백설기',
    nameEn: 'Baekseolgi',
    description: '순백의 쌀가루로 만든 전통 백설기. 부드럽고 담백하여 아이부터 어른까지 좋아하는 떡입니다.',
    price: 18000,
    originalPrice: null,
    category: 'traditional',
    vendorId: 2,
    image: 'https://images.unsplash.com/photo-1604498149220-bfb7c7cfd19b?w=600&h=450&fit=crop',
    tags: ['전통', '건강', '순수'],
    weight: '1kg',
    rating: 4.7,
    reviewCount: 89,
    isNew: false,
    isBest: false,
  },
  {
    id: 4,
    name: '꿀떡',
    nameEn: 'Honey Rice Cake',
    description: '국산 꿀을 듬뿍 넣어 달콤하고 쫄깃한 꿀떡. 어린이들이 특히 좋아하는 간식용 떡입니다.',
    price: 9000,
    originalPrice: 11000,
    category: 'traditional',
    vendorId: 3,
    image: 'https://images.unsplash.com/photo-1635355347994-b79177b77e5c?w=600&h=450&fit=crop',
    tags: ['달콤', '간식', '인기'],
    weight: '400g',
    rating: 4.6,
    reviewCount: 167,
    isNew: false,
    isBest: true,
  },
  {
    id: 5,
    name: '약식',
    nameEn: 'Yakshik',
    description: '밤, 대추, 잣을 넣고 참기름과 간장으로 윤기나게 만든 약식. 정월대보름 대표 음식입니다.',
    price: 25000,
    originalPrice: null,
    category: 'seasonal',
    vendorId: 2,
    image: 'https://images.unsplash.com/photo-1531263539449-56fdf29dfc4d?w=600&h=450&fit=crop',
    tags: ['명절', '프리미엄', '전통'],
    weight: '800g',
    rating: 4.8,
    reviewCount: 142,
    isNew: false,
    isBest: false,
  },
  {
    id: 6,
    name: '절편',
    nameEn: 'Jeolpyeon',
    description: '얇게 썰어낸 우아한 절편. 쑥, 오미자, 치자 등 천연 재료로 색을 내어 보기에도 아름답습니다.',
    price: 16000,
    originalPrice: null,
    category: 'premium',
    vendorId: 4,
    image: 'https://images.unsplash.com/photo-1724052526175-4a7332bd10e9?w=600&h=450&fit=crop',
    tags: ['프리미엄', '색동', '전통'],
    weight: '500g',
    rating: 4.7,
    reviewCount: 98,
    isNew: true,
    isBest: false,
  },
  {
    id: 7,
    name: '가래떡',
    nameEn: 'Garaetteok',
    description: '길게 뽑아낸 원통형 떡. 떡국, 떡볶이용으로 좋으며 신선하고 쫄깃합니다.',
    price: 7000,
    originalPrice: null,
    category: 'traditional',
    vendorId: 1,
    image: 'https://images.unsplash.com/photo-1652265541147-560e6464aaf3?w=600&h=450&fit=crop',
    tags: ['떡국', '떡볶이', '필수'],
    weight: '1kg',
    rating: 4.5,
    reviewCount: 203,
    isNew: false,
    isBest: true,
  },
  {
    id: 8,
    name: '호박떡',
    nameEn: 'Pumpkin Rice Cake',
    description: '달콤한 단호박을 듬뿍 넣어 만든 건강한 호박떡. 자연스러운 단맛과 부드러운 식감이 특징입니다.',
    price: 14000,
    originalPrice: 16000,
    category: 'premium',
    vendorId: 5,
    image: 'https://images.unsplash.com/photo-1702745100328-fe7a353d11e9?w=600&h=450&fit=crop',
    tags: ['건강', '단호박', '영양'],
    weight: '600g',
    rating: 4.6,
    reviewCount: 76,
    isNew: true,
    isBest: false,
  },
  {
    id: 9,
    name: '두텁떡',
    nameEn: 'Duteoptteok',
    description: '떡 사이에 고물을 켜켜이 넣어 두껍게 만든 두텁떡. 팥, 콩, 깨 고물의 조화가 일품입니다.',
    price: 20000,
    originalPrice: null,
    category: 'premium',
    vendorId: 4,
    image: 'https://images.unsplash.com/photo-1623133894375-ce20135ee521?w=600&h=450&fit=crop',
    tags: ['프리미엄', '전통', '고급'],
    weight: '700g',
    rating: 4.9,
    reviewCount: 54,
    isNew: false,
    isBest: false,
  },
  {
    id: 10,
    name: '딸기 떡케이크',
    nameEn: 'Strawberry Rice Cake',
    description: '생크림과 신선한 딸기를 듬뿍 올린 떡케이크. 생일, 기념일에 특별한 선물이 됩니다.',
    price: 35000,
    originalPrice: 40000,
    category: 'rice-cake',
    vendorId: 6,
    image: 'https://images.unsplash.com/photo-1612452556661-c36c39c4a128?w=600&h=450&fit=crop',
    tags: ['케이크', '생일', '기념일'],
    weight: '1.2kg',
    rating: 4.9,
    reviewCount: 312,
    isNew: true,
    isBest: true,
  },
  {
    id: 11,
    name: '망고 떡케이크',
    nameEn: 'Mango Rice Cake',
    description: '달콤한 망고와 부드러운 생크림의 환상 조합. 여름철 인기 떡케이크입니다.',
    price: 38000,
    originalPrice: null,
    category: 'rice-cake',
    vendorId: 6,
    image: 'https://images.unsplash.com/photo-1488477304112-4944851de03d?w=600&h=450&fit=crop',
    tags: ['케이크', '망고', '여름'],
    weight: '1.2kg',
    rating: 4.8,
    reviewCount: 189,
    isNew: true,
    isBest: false,
  },
  {
    id: 12,
    name: '프리미엄 선물세트',
    nameEn: 'Premium Gift Set',
    description: '송편, 인절미, 약식, 절편 등 인기 떡을 한 세트로 구성한 고급 선물세트. 명절 선물로 최고입니다.',
    price: 55000,
    originalPrice: 65000,
    category: 'gift',
    vendorId: 2,
    image: 'https://images.unsplash.com/photo-1547132703-1af228eaaada?w=600&h=450&fit=crop',
    tags: ['선물', '세트', '프리미엄'],
    weight: '2kg',
    rating: 5.0,
    reviewCount: 421,
    isNew: false,
    isBest: true,
  },
  {
    id: 13,
    name: '건강 잡곡떡',
    nameEn: 'Multi-grain Rice Cake',
    description: '현미, 흑미, 보리 등 다양한 잡곡을 넣어 만든 건강 떡. 영양 만점, 맛도 만점입니다.',
    price: 13000,
    originalPrice: null,
    category: 'premium',
    vendorId: 5,
    image: 'https://images.unsplash.com/photo-1691171047409-89b77cd1285b?w=600&h=450&fit=crop',
    tags: ['건강', '잡곡', '영양'],
    weight: '600g',
    rating: 4.5,
    reviewCount: 67,
    isNew: false,
    isBest: false,
  },
  {
    id: 14,
    name: '쑥떡',
    nameEn: 'Mugwort Rice Cake',
    description: '봄에 채취한 신선한 쑥을 듬뿍 넣은 쑥떡. 쑥향이 가득하고 건강에도 좋습니다.',
    price: 11000,
    originalPrice: null,
    category: 'seasonal',
    vendorId: 3,
    image: 'https://images.unsplash.com/photo-1598149281008-945e78df18f8?w=600&h=450&fit=crop',
    tags: ['쑥', '봄', '건강'],
    weight: '500g',
    rating: 4.7,
    reviewCount: 145,
    isNew: false,
    isBest: false,
  },
  {
    id: 15,
    name: '전통 선물세트 (소)',
    nameEn: 'Traditional Gift Set (S)',
    description: '부담 없이 선물하기 좋은 전통 떡 선물세트. 송편, 인절미, 백설기가 들어있습니다.',
    price: 28000,
    originalPrice: 32000,
    category: 'gift',
    vendorId: 1,
    image: 'https://images.unsplash.com/photo-1711837690911-3a8d8262053b?w=600&h=450&fit=crop',
    tags: ['선물', '세트', '전통'],
    weight: '1kg',
    rating: 4.8,
    reviewCount: 234,
    isNew: false,
    isBest: true,
  },
]
