// 입점 업체 데이터 — 떡담 플랫폼
// 각 업체는 id, name, description, image, location, rating, reviewCount, specialties, established, isVerified 필드를 포함

export const vendors = [
  {
    id: 1,
    name: '할매네 떡방',
    description: '30년 전통의 손맛. 어머니의 사랑을 담은 정성 가득한 떡을 만듭니다. 3대째 이어온 전통 방식 고수.',
    image: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=600&h=450&fit=crop',
    location: '서울 종로구',
    rating: 4.9,
    reviewCount: 256,
    specialties: ['송편', '인절미', '백설기'],
    established: '1995',
    isVerified: true,
  },
  {
    id: 2,
    name: '정성떡집',
    description: '명절 떡 전문점. 최고급 재료만 엄선하여 정성껏 만든 프리미엄 떡을 제공합니다.',
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=600&h=450&fit=crop',
    location: '경기 수원시',
    rating: 4.8,
    reviewCount: 189,
    specialties: ['약식', '백설기', '선물세트'],
    established: '2005',
    isVerified: true,
  },
  {
    id: 3,
    name: '우리떡',
    description: '국내산 재료만 사용하는 깨끗한 떡집. 어린이부터 어른까지 안심하고 먹을 수 있습니다.',
    image: 'https://images.unsplash.com/photo-1559329007-40df8a9345d8?w=600&h=450&fit=crop',
    location: '인천 부평구',
    rating: 4.7,
    reviewCount: 142,
    specialties: ['꿀떡', '쑥떡', '가래떡'],
    established: '2010',
    isVerified: true,
  },
  {
    id: 4,
    name: '고품격 떡공방',
    description: '현대적 감각을 더한 프리미엄 떡. 전통의 맛과 세련된 비주얼을 동시에 추구합니다.',
    image: 'https://images.unsplash.com/photo-1581579438747-1dc8d17bbce4?w=600&h=450&fit=crop',
    location: '서울 강남구',
    rating: 4.9,
    reviewCount: 98,
    specialties: ['절편', '두텁떡', '떡케이크'],
    established: '2018',
    isVerified: true,
  },
  {
    id: 5,
    name: '건강한떡',
    description: '유기농, 무농약 재료로 만드는 건강 떡 전문점. 당뇨, 다이어트 고객을 위한 저당 떡도 판매.',
    image: 'https://images.unsplash.com/photo-1587334207976-e7d52adaef5c?w=600&h=450&fit=crop',
    location: '경기 성남시',
    rating: 4.6,
    reviewCount: 76,
    specialties: ['호박떡', '잡곡떡', '현미떡'],
    established: '2015',
    isVerified: true,
  },
  {
    id: 6,
    name: '케이크떡 공방',
    description: '생일, 기념일 특화 떡케이크 전문점. SNS에서 핫한 예쁜 떡케이크를 만날 수 있습니다.',
    image: 'https://images.unsplash.com/photo-1535254973040-607b474cb50d?w=600&h=450&fit=crop',
    location: '서울 마포구',
    rating: 5.0,
    reviewCount: 312,
    specialties: ['딸기 떡케이크', '망고 떡케이크', '커스텀 케이크'],
    established: '2020',
    isVerified: true,
  },
]
